// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           29
// Async Callback (empty):               1
// Total number of exported functions:  31

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    manager
    (
        addAdmin
        removeAdmin
        forwardToken
        executeTicket
        createEntity
        upgradeEntity
        setFeatures
        setEntityCreationCost
        setDailyBaseCost
        setDailyFeatureCost
        getAdmins
        getEntities
        getEntityTemplateAddress
        getTrustedHostAddress
        getCostTokenId
        getEntityCreationCost
        getBaseDailyCost
        getFeatureDailyCost
        getFeatures
        initCreditsModule
        setCreditsBonusFactor
        boost
        boostWithSwap
        registerExternalBoost
        getCredits
        getCreditsInfo
        initDexModule
        initOrgModule
        forwardCostTokensToOrg
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
