////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    entity
    (
        callBack
        assignRole
        changeGovToken
        changeMinProposalVoteWeight
        changeQuorum
        changeVotingPeriodMinutes
        createPermission
        createPolicyForAll
        createPolicyForOne
        createPolicyQuorum
        createPolicyWeighted
        createRole
        execute
        getGovTokenId
        getGovTokenSupply
        getMinProposalVoteWeight
        getPermissions
        getPolicies
        getProposal
        getProposalIdCounter
        getProposalSignatureRoleCounts
        getProposalSigners
        getProposalStatus
        getProposalVotes
        getProtectedVoteTokens
        getQuorum
        getRoleMemberAmount
        getRoles
        getSealed
        getTrustedHostAddress
        getUserRoles
        getUsersForRole
        getVersion
        getVotingPeriodMinutes
        getWithdrawableProposalIds
        issueGovToken
        propose
        seal
        setGovTokenLocalRoles
        sign
        voteAgainst
        voteFor
        withdraw
    )
}
